from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
from typing import Optional, List, Dict, Any
import json
import os
import pandas as pd
from dashboard_analysis import LenovoDashboardAnalysis
import openai
import re
from dotenv import load_dotenv
load_dotenv()

client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

app = FastAPI()

# Get the current directory
current_dir = os.path.dirname(os.path.abspath(__file__))

# Mount the static files directory
app.mount("/static", StaticFiles(directory=current_dir), name="static")

# Configure CORS to allow requests from your frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, replace with specific origin
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve the index.html file at the root URL
@app.get("/")
async def read_root():
    return FileResponse(os.path.join(current_dir, 'index.html'))

# Example model for request/response
class Message(BaseModel):
    text: str
    user_id: Optional[str] = None

# Describe your datasets for the AI
DATA_DESCRIPTION = """
You have the following datasets:
1. 'dataset/Sales datasets/Laptop_brands_daily_spend_new.xlsx' with columns: Date, Brand, Channel, Spend, Facebook, Instagram, LinkedIn, TikTok, X, YouTube, OTT, Desktop Display, Desktop Video, Mobile Display, Mobile Video, Snapchat, Search, Display, Video, Social.
2. 'dataset/Semrush dataset/Organic_Search_Lenovo.xlsx', 'Organic_Search_HP.xlsx', 'Organic_Search_Dell.xlsx' with columns: Keyword, Traffic, Number of Keywords, Positions with commercial intents in top 20, etc.
3. 'dataset/Google trends dataset/Comparison.xlsx', 'Web_Data.xlsx', 'Yt Search.xlsx' with columns: Keyword, Search Volume, etc.
You can use Pandas to load and analyze these files. Answer the user's question using these datasets. If possible, provide a Pandas code snippet to get the answer.
If the answer can be visualized, return a JSON object with the following structure:
{
  "chart_name": "line_chart" or "grouped_bar_chart" or "scatter_chart",
  "x-axis": {"name": "...", "values": [...] },
  "y-axis": {"name": "...", "values": {...} }
}
Return the JSON object on a new line after your answer.
"""

def ask_openai(question, data_description=DATA_DESCRIPTION):
    prompt = f"""
You are a data analyst. Here is a description of the available datasets:
{data_description}
Answer the user's question: '{question}'

If the answer can be visualized, return:
- A short, catchy chart title (start the line with 'Title:')
- A subtitle describing what the chart shows (start the line with 'Subtitle:')
- 2-3 bullet-point insights summarizing the key findings (start the section with 'Insights:' and use '-' for each bullet)
- A JSON object with chart_name, x-axis, and y-axis as before (on a new line after your answer)
"""
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

def extract_chart_json(llm_response):
    match = re.search(r'({[\s\S]*})', llm_response)
    if match:
        try:
            chart_json = json.loads(match.group(1))
            return chart_json
        except Exception:
            return None
    return None

def parse_llm_response(llm_response):
    # Extract title
    title_match = re.search(r"Title:\s*(.*)", llm_response)
    title = title_match.group(1).strip() if title_match else "AI-generated answer"

    # Extract subtitle
    subtitle_match = re.search(r"Subtitle:\s*(.*)", llm_response)
    subtitle = subtitle_match.group(1).strip() if subtitle_match else "This answer was generated by a Google Generative AI model (Gemini/PaLM)."

    # Extract insights (as a list)
    insights_match = re.search(r"Insights:\s*((?:- .*(?:\n|$))+)", llm_response)
    if insights_match:
        insights = [line[2:].strip() for line in insights_match.group(1).strip().split('\n') if line.startswith('- ')]
    else:
        insights = []

    # Extract chart JSON
    chart_json = extract_chart_json(llm_response)

    return title, subtitle, insights, chart_json

@app.get("/api/keyword-gaps")
async def get_keyword_gaps():
    data = {
        "keywords": ["Business Laptops", "Gaming Laptops", "Workstation", "Convertible"],
        "lenovo_performance": [85, 60, 75, 80],
        "competitor_avg": [70, 75, 65, 70]
    }
    return {
        "question": "Identify keywords where competitors (Dell/HP) dominate but Lenovo underperforms",
        "answer": {
            "title": "Strategic Keyword Performance Analysis",
            "subtitle": "Identifying Critical Search Term Opportunities and Competitive Gaps",
            "insights": [
                "Lenovo demonstrates strong performance in business laptop keywords (85/100), outperforming competitors by 15 points",
                "Gaming laptop keywords present the largest opportunity gap, with Lenovo trailing competitors by 15 points",
                "Overall balanced performance across workstation and convertible categories"
            ]
        },
        "chart_name": "grouped_bar_chart",
        "x-axis": {
            "name": "keywords",
            "values": data["keywords"]
        },
        "y-axis": {
            "name": "Performance scores (0-100)",
            "values": {
                "lenovo_performance": data["lenovo_performance"],
                "competitor_avg": data["competitor_avg"]
            }
        }
    }

@app.get("/api/ad-spend-efficiency")
async def get_ad_spend_efficiency():
    return {
        "question": "Compare ad spend efficiency across competitors in critical markets",
        "answer": {
            "title": "Channel Performance and Investment Analysis",
            "subtitle": "Optimizing Marketing Spend Across Digital Channels",
            "insights": [
                "Display advertising shows the highest efficiency ratio compared to competitors",
                "Mobile channels demonstrate stronger ROI than desktop channels",
                "Social media spend shows room for optimization and increased investment"
            ]
        },
        "chart_name": "grouped_bar_chart",
        "x-axis": {
            "name": "channels",
            "values": ["Social", "Video", "Display", "Search"]
        },
        "y-axis": {
            "name": "Ad Spend ($)",
            "values": {
                "lenovo_spend": [158.83, 6500000, 120000, 450000],
                "competitor_avg": [120.50, 6700000, 150000, 500000]
            }
        }
    }

@app.get("/api/youtube-trends")
async def get_youtube_trends():
    return {
        "question": "Identify untapped YouTube search trends where Lenovo's content is underrepresented",
        "answer": {
            "title": "Content Strategy and Market Presence Analysis",
            "subtitle": "Identifying Content Opportunities in Key Product Categories",
            "insights": [
                "Gaming and workstation categories show the largest content gaps",
                "Business laptop content demonstrates strong market presence",
                "Opportunity to expand content in convertible and Chromebook segments"
            ]
        },
        "chart_name": "grouped_bar_chart",
        "x-axis": {
            "name": "categories",
            "values": ["Gaming Laptops", "Business Laptops", "Workstation", "Convertible"]
        },
        "y-axis": {
            "name": "Content Coverage Score",
            "values": {
                "lenovo_content": [10, 20, 5, 8],
                "competitor_avg": [130, 100, 85, 60]
            }
        }
    }

@app.get("/api/competitor-impact")
async def get_competitor_impact():
    return {
        "question": "Analyze correlation between competitor ad spend and Lenovo's visibility",
        "answer": {
            "title": "Competitive Landscape and Market Dynamics",
            "subtitle": "Understanding Competitor Influence on Market Position",
            "insights": [
                "Social media campaigns show the highest correlation with market impact",
                "Video content has a delayed but significant effect on market position",
                "Display advertising shows immediate but short-term impact"
            ]
        },
        "chart_name": "line_chart",
        "x-axis": {
            "name": "time_periods",
            "values": ["0 days", "7 days", "14 days", "30 days"]
        },
        "y-axis": {
            "name": "Correlation Score",
            "values": {
                "social_impact": [0.3, 0.4, 0.2, 0.1],
                "video_impact": [0.2, 0.3, 0.1, 0.0],
                "display_impact": [0.1, 0.2, 0.0, -0.1]
            }
        }
    }

@app.get("/api/opportunity-keywords")
async def get_opportunity_keywords():
    return {
        "question": "Identify low-CPC, high-opportunity keywords",
        "answer": {
            "title": "Strategic Keyword Investment Analysis",
            "subtitle": "Identifying High-Value, Low-Competition Keywords",
            "insights": [
                "Business laptop keywords show the highest opportunity scores",
                "Gaming and workstation keywords present balanced competition",
                "Long-tail keywords in convertible category show untapped potential"
            ]
        },
        "chart_name": "scatter_chart",
        "x-axis": {
            "name": "search_volume",
            "values": [10000, 8000, 6000, 4000]
        },
        "y-axis": {
            "name": "Opportunity Score",
            "values": {
                "keywords": ["ThinkPad", "Legion", "Yoga", "IdeaPad"],
                "scores": [85, 75, 65, 55]
            }
        }
    }

@app.post("/api/message")
async def message_endpoint(request: Request):
    data = await request.json()
    question = data.get("question", "").lower()
    analyzer = LenovoDashboardAnalysis()

    try:
        if "ad spend" in question or "spend efficiency" in question:
            df = analyzer.analyze_ad_spend_efficiency()
            if not df.empty:
                top_channel = df.loc[df['lenovo_spend'].idxmin(), 'channel'] if 'channel' in df else 'N/A'
                highest_spend_channel = df.loc[df['lenovo_spend'].idxmax(), 'channel'] if 'channel' in df else 'N/A'
                avg_competitor = df['competitor_avg'].mean() if 'competitor_avg' in df else 0
                insights = [
                    f"{top_channel} shows the highest efficiency for Lenovo.",
                    f"{highest_spend_channel} has the highest spend and may need optimization.",
                    f"Average competitor spend is ${avg_competitor:,.0f} across all channels."
                ]
            else:
                insights = ["No data available for ad spend analysis."]
            return {
                "question": data.get("question", ""),
                "answer": {
                    "title": "Ad Spend Efficiency Analysis",
                    "subtitle": "Channel-wise Comparison of Ad Spend",
                    "insights": insights
                },
                "chart_name": "grouped_bar_chart",
                "x-axis": {"name": "channels", "values": df['channel'].tolist() if 'channel' in df else []},
                "y-axis": {"name": "Ad Spend ($)", "values": {"lenovo_spend": df['lenovo_spend'].tolist() if 'lenovo_spend' in df else [], "competitor_avg": df['competitor_avg'].tolist() if 'competitor_avg' in df else []}}
            }
        elif "youtube" in question or "video trends" in question:
            df = analyzer.analyze_youtube_trends()
            if not df.empty:
                top_cat = df.loc[df['content_gap'].idxmax(), 'category'] if 'content_gap' in df else 'N/A'
                top_gap = df['content_gap'].max() if 'content_gap' in df else 0
                insights = [
                    f"{top_cat} has the largest content gap of {top_gap}.",
                    "Significant opportunity in underrepresented topics.",
                    "Need to expand content coverage in key areas."
                ]
            else:
                insights = ["No data available for YouTube trends analysis."]
            return {
                "question": data.get("question", ""),
                "answer": {
                    "title": "YouTube Content Gap Analysis",
                    "subtitle": "Search Interest vs Content Coverage",
                    "insights": insights
                },
                "chart_name": "grouped_bar_chart",
                "x-axis": {"name": "categories", "values": df['category'].tolist() if 'category' in df else []},
                "y-axis": {"name": "Content Coverage Score", "values": {"lenovo_content": df['lenovo_content_count'].tolist() if 'lenovo_content_count' in df else [], "competitor_avg": df['competitor_avg_content_count'].tolist() if 'competitor_avg_content_count' in df else []}}
            }
        elif "keyword gap" in question or "underperform" in question:
            df = analyzer.analyze_keyword_gaps()
            if not df.empty:
                top_gap_keyword = df.loc[df['gap_score'].idxmax(), 'keyword'] if 'gap_score' in df else 'N/A'
                top_gap = df['gap_score'].max() if 'gap_score' in df else 0
                insights = [
                    f"{top_gap_keyword} has the largest performance gap ({top_gap:.1f}).",
                    "Opportunity for improvement in high-gap keywords.",
                    "Competitors dominate in certain segments."
                ]
            else:
                insights = ["No data available for keyword gap analysis."]
            return {
                "question": data.get("question", ""),
                "answer": {
                    "title": "Keyword Performance Gaps",
                    "subtitle": "Comparison of Lenovo vs Competitor Keyword Performance",
                    "insights": insights
                },
                "chart_name": "grouped_bar_chart",
                "x-axis": {"name": "keywords", "values": df['keyword'].tolist() if 'keyword' in df else []},
                "y-axis": {"name": "Performance scores (0-100)", "values": {"lenovo_performance": df['lenovo_performance'].tolist() if 'lenovo_performance' in df else [], "competitor_avg": df['competitor_avg'].tolist() if 'competitor_avg' in df else []}}
            }
        elif "competitor impact" in question or "correlation" in question:
            df = analyzer.analyze_competitor_impact()
            if not df.empty:
                max_corr = df[['social_impact', 'video_impact', 'display_impact']].max().max() if {'social_impact','video_impact','display_impact'}.issubset(df.columns) else 0
                max_channel = df[['social_impact', 'video_impact', 'display_impact']].max().idxmax() if {'social_impact','video_impact','display_impact'}.issubset(df.columns) else 'N/A'
                insights = [
                    f"{max_channel} shows the highest correlation ({max_corr:.2f}) with Lenovo's visibility.",
                    "Dell's impact is minimal across channels.",
                    "Correlation varies by channel and time period."
                ]
            else:
                insights = ["No data available for competitor impact analysis."]
            return {
                "question": data.get("question", ""),
                "answer": {
                    "title": "Competitor Impact Analysis",
                    "subtitle": "Correlation between Ad Spend and Visibility",
                    "insights": insights
                },
                "chart_name": "line_chart",
                "x-axis": {"name": "time_periods", "values": df['time_period'].tolist() if 'time_period' in df else []},
                "y-axis": {"name": "Correlation Score", "values": {"social_impact": df['social_impact'].tolist() if 'social_impact' in df else [], "video_impact": df['video_impact'].tolist() if 'video_impact' in df else [], "display_impact": df['display_impact'].tolist() if 'display_impact' in df else []}}
            }
        elif "opportunity keyword" in question or "growth keyword" in question:
            df = analyzer.analyze_opportunity_keywords()
            if not df.empty:
                top_keyword = df.loc[df['opportunity_score'].idxmax(), 'keyword'] if 'opportunity_score' in df else 'N/A'
                top_score = df['opportunity_score'].max() if 'opportunity_score' in df else 0
                insights = [
                    f"{top_keyword} has the highest opportunity score ({top_score:.1f}).",
                    "Gaming laptop keywords show high potential.",
                    "Other segments offer additional growth."
                ]
            else:
                insights = ["No data available for opportunity keyword analysis."]
            return {
                "question": data.get("question", ""),
                "answer": {
                    "title": "Keyword Opportunities",
                    "subtitle": "High-Value Keywords with Growth Potential",
                    "insights": insights
                },
                "chart_name": "scatter_chart",
                "x-axis": {"name": "search_volume", "values": df['search_volume'].tolist() if 'search_volume' in df else []},
                "y-axis": {"name": "Opportunity Score", "values": {"keywords": df['keyword'].tolist() if 'keyword' in df else [], "scores": df['opportunity_score'].tolist() if 'opportunity_score' in df else []}}
            }
        else:
            # Use OpenAI to answer any other question about the dataset
            ai_response = ask_openai(data.get("question", ""))
            title, subtitle, insights, chart_json = parse_llm_response(ai_response)
            if chart_json:
                return {
                    "question": data.get("question", ""),
                    "answer": {
                        "title": title,
                        "subtitle": subtitle,
                        "insights": insights
                    },
                    "chart_name": chart_json.get("chart_name"),
                    "x-axis": chart_json.get("x-axis", {"name": "", "values": []}),
                    "y-axis": chart_json.get("y-axis", {"name": "", "values": {}})
                }
            else:
                return {
                    "question": data.get("question", ""),
                    "answer": {
                        "title": title,
                        "subtitle": subtitle,
                        "insights": insights if insights else [ai_response]
                    },
                    "chart_name": None,
                    "x-axis": {"name": "", "values": []},
                    "y-axis": {"name": "", "values": {}}
                }
    except Exception as e:
        return {
            "question": data.get("question", ""),
            "answer": {
                "title": "Error",
                "subtitle": "There was a problem analyzing your data.",
                "insights": [str(e)]
            },
            "chart_name": None,
            "x-axis": {"name": "", "values": []},
            "y-axis": {"name": "", "values": {}}
        }